server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-jt-web #服務名稱"唯一"不能動複
  registry:
    address: zookeeper://10.211.55.6:2181?backup=10.211.55.6:2182,10.211.55.6:2183
#    address: zookeeper://54.180.29.161:2181