server:
  port: 8094
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 12345

#Springboot容器整合dubbo    
dubbo:
  scan:
    basePackages: com.jt  #包掃描dubbo的@Service註解
  application:
    name: provider-cart   #提供者 服務的名稱
  registry: #鏈接zookeeper
    address: zookeeper://10.211.55.6:2181?backup=10.211.55.6:2182,10.211.55.6:2183
  protocol:
    name: dubbo
    port: 20881 #服務通信的端口 消費者鏈接提供者的端口 每個服務的端口必須不同 這裡要跟單點登錄的port不一樣
    
#mybatis-plus配置
mybatis-plus:  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 